# Generated by Django 5.0.7 on 2024-07-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('date_of_joining', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.project')),
            ],
        ),
    ]
